# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(default=1)),
                ('language', models.CharField(default='DE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('CVC', models.CharField(max_length=200)),
                ('gr', models.CharField(max_length=200)),
                ('ph', models.CharField(max_length=200)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Database.Dictionary')),
            ],
        ),
    ]
