# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='CVC',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='ph',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='word',
            field=models.CharField(default='', max_length=200),
        ),
    ]
