# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_auto_20170607_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='HFW',
            field=models.BooleanField(default=True),
        ),
    ]
