# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_entry_hfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='HFW',
            field=models.BooleanField(default=False),
        ),
    ]
