# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinguisticQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('question', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LinguisticRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(verbose_name='Missing Description')),
                ('rule', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
