# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wordout', '0003_auto_20170606_0947'),
        ('Linguistics', '0003_auto_20170605_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinguisticQuestion',
        ),
    ]
