# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Games', '0004_auto_20170605_0827'),
        ('Linguistics', '0002_auto_20170605_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Association', max_length=200)),
                ('gameType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.GameType')),
                ('linguistic_rule_input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input', to='Linguistics.LinguisticRule')),
                ('linguistic_rule_output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='Linguistics.LinguisticRule')),
                ('linguistic_rule_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Linguistics.LinguisticQuestion')),
            ],
        ),
    ]
