# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wordout', '0003_auto_20170606_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationtable',
            name='linguistic_rule_question',
        ),
        migrations.AddField(
            model_name='associationtable',
            name='question',
            field=models.CharField(default='Question', max_length=200),
        ),
    ]
