# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametype',
            name='linguistic_rule_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input', to='Linguistics.LinguisticRule'),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='linguistic_rule_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output', to='Linguistics.LinguisticRule'),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='linguistic_rule_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Linguistics.LinguisticQuestion'),
        ),
    ]
