# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_auto_20170604_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametype',
            name='description',
            field=models.TextField(default='Missing Description'),
        ),
    ]
