# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0005_auto_20170609_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametype',
            name='name',
            field=models.CharField(default='NoName', max_length=200, null=True),
        ),
    ]
