# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('level', models.IntegerField(default='', null=True)),
                ('list', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVCLevels',
            fields=[
                ('level_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Levels.Level')),
            ],
            bases=('Levels.level',),
        ),
        migrations.CreateModel(
            name='LetterLevels',
            fields=[
                ('level_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Levels.Level')),
            ],
            bases=('Levels.level',),
        ),
        migrations.CreateModel(
            name='WordLevels',
            fields=[
                ('level_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Levels.Level')),
            ],
            bases=('Levels.level',),
        ),
    ]
