# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Levels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='list',
            field=models.TextField(default='', null=True),
        ),
    ]
